### PR TITLE
Fixed for dgram needing buffer length

### PR DESCRIPTION
**Pull request by blha303**
Encountered a RangeError on the below line, looked up similar code on StackOverflow, found that dgram needs a buffer length

### CODE REVIEW

**Comment by sirsquidness** [comment]
Hey, thanks for taking the time to contribute! :D

From what I interpret [of the node udp socker docs](https://nodejs.org/api/dgram.html#dgram_socket_send_msg_offset_length_port_address_callback) the start position and length should be optional fields. I wonder if perhaps this is changed behaviour in some version of node? Or I wonder if there's a bug where a not-a-buffer or 0 length buffer is being passed in that somehow causes the RangeError.

So of curiosity, which version of node are you using? And how often were you seeing this error pop up, and did this patch completely remove all symptoms of errors?

**Comment by blha303** [comment]
The error was preventing the program from doing anything, it returned "Could not send" repeatedly. After removing the try{}catch(e){}, we had this error http://paste.ee/p/2iMPy. Node version 4.2.6

**Comment by blha303** [comment]
This change removed the error entirely, the program works great now, it's very cool :D

**Comment by sirsquidness** [comment]
Aha! I used node 5 when developing this. In node 4, the arguments were not optional. I'll merge this when I'm next in front of my PC. Thanks again :)

**Pull request merged**
